// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FileExists(arg1:string):Promise<boolean>;

export function GetArch():Promise<string>;

export function GetOS():Promise<string>;

export function ReadFile(arg1:string):Promise<string>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;
