// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FileExists(arg1) {
  return window['go']['bind']['Common']['FileExists'](arg1);
}

export function GetArch() {
  return window['go']['bind']['Common']['GetArch']();
}

export function GetOS() {
  return window['go']['bind']['Common']['GetOS']();
}

export function ReadFile(arg1) {
  return window['go']['bind']['Common']['ReadFile'](arg1);
}

export function WriteFile(arg1, arg2) {
  return window['go']['bind']['Common']['WriteFile'](arg1, arg2);
}
