// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {data} from '../models';

export function DeleteServerConfig(arg1:string):Promise<void>;

export function DeleteWorkspace(arg1:string):Promise<void>;

export function GetWorkspace(arg1:string):Promise<data.Workspace>;

export function LoadServerConfigs():Promise<Array<data.ServerConfig>>;

export function LoadWorkspaces():Promise<Array<data.Workspace>>;

export function SaveServerConfig(arg1:data.ServerConfig):Promise<void>;

export function SaveWorkspace(arg1:data.Workspace):Promise<void>;
