// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteServerConfig(arg1) {
  return window['go']['bind']['Data']['DeleteServerConfig'](arg1);
}

export function DeleteWorkspace(arg1) {
  return window['go']['bind']['Data']['DeleteWorkspace'](arg1);
}

export function GetWorkspace(arg1) {
  return window['go']['bind']['Data']['GetWorkspace'](arg1);
}

export function LoadServerConfigs() {
  return window['go']['bind']['Data']['LoadServerConfigs']();
}

export function LoadWorkspaces() {
  return window['go']['bind']['Data']['LoadWorkspaces']();
}

export function SaveServerConfig(arg1) {
  return window['go']['bind']['Data']['SaveServerConfig'](arg1);
}

export function SaveWorkspace(arg1) {
  return window['go']['bind']['Data']['SaveWorkspace'](arg1);
}
