// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {data} from '../models';
import {common} from '../models';

export function GetServerInstance(arg1:string):Promise<data.ServerInstance>;

export function GetWorkspaceServerInstances(arg1:string):Promise<Array<data.ServerInstance>>;

export function NewServerInstance(arg1:common.ServerConfig):Promise<data.ServerInstance>;

export function StartServerInstance(arg1:string):Promise<void>;

export function StartWorkspace(arg1:string):Promise<void>;

export function StopServerInstance(arg1:string):Promise<void>;
