// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetServerInstance(arg1) {
  return window['go']['bind']['Manager']['GetServerInstance'](arg1);
}

export function GetWorkspaceServerInstances(arg1) {
  return window['go']['bind']['Manager']['GetWorkspaceServerInstances'](arg1);
}

export function NewServerInstance(arg1) {
  return window['go']['bind']['Manager']['NewServerInstance'](arg1);
}

export function StartServerInstance(arg1) {
  return window['go']['bind']['Manager']['StartServerInstance'](arg1);
}

export function StartWorkspace(arg1) {
  return window['go']['bind']['Manager']['StartWorkspace'](arg1);
}

export function StopServerInstance(arg1) {
  return window['go']['bind']['Manager']['StopServerInstance'](arg1);
}
