// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadSettings() {
  return window['go']['bind']['Setting']['LoadSettings']();
}

export function SaveSettings(arg1) {
  return window['go']['bind']['Setting']['SaveSettings'](arg1);
}
