// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {data} from '../models';

export function LoadSettings():Promise<data.Settings>;

export function SaveSettings(arg1:data.Settings):Promise<void>;
